spring:
  datasource:
    url: ${MEDTECH_DB_URL}
    username: ${MEDTECH_DB_USER}
    password: ${MEDTECH_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false
  jackson:
    serialization:
      indent-output: false

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

medtech:
  security:
    jwt:
      secret: ${MEDTECH_SECURITY_JWT_SECRET}
    cookie-secure: true
    cors:
      allowed-origins:
        - https://medtech.mk
        - https://www.medtech.mk

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    com.medtech: INFO
    org.hibernate.SQL: WARN
