package com.medtech.fixture;

import com.medtech.domain.entity.Appointment;
import com.medtech.domain.entity.Doctor;
import com.medtech.domain.entity.Hospital;
import com.medtech.domain.entity.MedicalRecord;
import com.medtech.domain.entity.Patient;
import com.medtech.domain.entity.Prescription;
import com.medtech.domain.entity.Referral;
import com.medtech.domain.entity.User;
import com.medtech.domain.vo.AppointmentStatus;
import com.medtech.domain.vo.HospitalStatus;
import com.medtech.domain.vo.PrescriptionStatus;
import com.medtech.domain.vo.ReferralStatus;
import com.medtech.domain.vo.ReferralType;
import com.medtech.domain.vo.UserRole;
import com.medtech.domain.vo.UserStatus;

import java.lang.reflect.Field;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Test data builders. Identity fields are normally generated by the database;
 * tests inject them via reflection because {@code @GeneratedValue} obviously
 * doesn't fire when we never round-trip through a real {@code EntityManager}.
 */
public final class Entities {

    private Entities() {}

    public static User user(Long id, UserRole role) {
        User u = new User();
        setId(u, "id", id);
        u.setEmail("user" + id + "@medtech.mk");
        u.setPasswordHash("$2a$hash");
        u.setFirstName("First" + id);
        u.setLastName("Last" + id);
        u.setRole(role);
        u.setStatus(UserStatus.ACTIVE);
        return u;
    }

    public static Hospital hospital(Long id) {
        Hospital h = new Hospital();
        setId(h, "id", id);
        h.setName("Hospital " + id);
        h.setCity("Skopje");
        h.setAddress("Some street");
        h.setStatus(HospitalStatus.ACTIVE);
        return h;
    }

    public static Patient patient(Long id, User user) {
        Patient p = new Patient();
        setId(p, "id", id);
        p.setUser(user);
        p.setDateOfBirth(LocalDate.of(1990, 1, 1));
        return p;
    }

    public static Doctor doctor(Long id, User user, Hospital hospital) {
        Doctor d = new Doctor();
        setId(d, "id", id);
        d.setUser(user);
        d.setHospital(hospital);
        d.setLicenseNumber("LIC-" + id);
        d.setSpecialization("General");
        d.setStatus(UserStatus.ACTIVE);
        return d;
    }

    public static Appointment appointment(Long id, Patient patient, Doctor doctor,
                                          LocalDate date, String time,
                                          AppointmentStatus status) {
        Appointment a = new Appointment();
        setId(a, "id", id);
        a.setPatient(patient);
        a.setDoctor(doctor);
        a.setHospital(doctor.getHospital());
        a.setAppointmentDate(date);
        a.setAppointmentTime(LocalTime.parse(time));
        a.setDurationMinutes(30);
        a.setStatus(status);
        return a;
    }

    public static MedicalRecord medicalRecord(Long id, Patient patient, Doctor doctor, Instant createdAt) {
        MedicalRecord r = new MedicalRecord();
        setId(r, "id", id);
        r.setPatient(patient);
        r.setDoctor(doctor);
        r.setHospital(doctor.getHospital());
        r.setClinicalNotes("notes");
        setId(r, "createdAt", createdAt);
        return r;
    }

    public static Prescription prescription(Long id, Patient patient, Doctor doctor,
                                            int allowed, int used,
                                            LocalDate endDate, PrescriptionStatus status) {
        Prescription rx = new Prescription();
        setId(rx, "id", id);
        rx.setPatient(patient);
        rx.setDoctor(doctor);
        rx.setMedicationName("Aspirin");
        rx.setDosage("100mg");
        rx.setFrequency("1/day");
        rx.setStartDate(LocalDate.now().minusDays(1));
        rx.setEndDate(endDate);
        rx.setRefillsAllowed(allowed);
        rx.setRefillsUsed(used);
        rx.setStatus(status);
        return rx;
    }

    public static Referral referral(Long id, Doctor doctor, Patient patient,
                                    ReferralType type, ReferralStatus status) {
        Referral r = new Referral();
        setId(r, "id", id);
        r.setDoctor(doctor);
        r.setPatient(patient);
        r.setReferralType(type);
        r.setReferredTo("General Hospital");
        r.setScheduledDate(LocalDate.now().plusDays(14));
        r.setStatus(status);
        r.setReferralNumber("UP-2026-" + String.format("%03d", id));
        return r;
    }

    private static void setId(Object target, String name, Object value) {
        try {
            Field f = target.getClass().getDeclaredField(name);
            f.setAccessible(true);
            f.set(target, value);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
    }
}
